### ISSUE TITLE
Possibility for a 'stacked' bar graph?

### ISSUE THREAD

**Issue by joverbee** [emoncms/graph#18]
maybe this is already possible and I didnt notice it, but I would like to display a bar graph where each data set is added onto one large bar in different colors rather than the superimposed bars in different colors now. (Similar than the graphs in 'sustainable energy without the hot air')
Will take a look at where in the code this could be achieved.

**Comment by glynhudson** [comment]
Yes, this is already possible. The required changes are currently in the latest master branch. Stacking support was added by @CDuffers, see: https://github.com/emoncms/graph/pull/17

**Comment by joverbee** [comment]
Great! indeed in the code it seemed to be there already. I'll try it out. Thanks @CDuffers

Op 7 jan. 2018 om 19:46 heeft Glyn Hudson <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Yes, this is already possible. The required changes are currently in the latest master branch. Stacking support was added by @CDuffers<https://github.com/cduffers>, see: #17<https://github.com/emoncms/graph/pull/17>
