### ISSUE TITLE
Right colomumn with checkboxes doesnt appear

### ISSUE THREAD

**Issue by 3raider** [emoncms/graph#2]
Dear developers, faced with problem that choosing second axis unavailible with long feed's names. Scrolling of frame doesnt helps
![1](https://cloud.githubusercontent.com/assets/19341839/15241490/e22fae50-18f8-11e6-9305-a07ab1ce70e4.jpg)
![2](https://cloud.githubusercontent.com/assets/19341839/15241489/e22f363c-18f8-11e6-9595-fe2c9fe72cc5.jpg)

**Comment by TrystanLea** [comment]
Sorry @3raider, I think this one got fixed, tested on the latest and it seems to hide the overflow on the names correctly
