### ISSUE TITLE
Collapsing lefthand panel and maximizing graph widths

### ISSUE THREAD

**Issue by pb66** [emoncms/graph#25]
I would really like to be able to collapse the lefthand panel after selecting feeds or a saved graph to give me more screen for the graph itself.

I get why it's there by default, but I would say I spend 99% of my time playing with the graphing and ignoring the lefthand panel, the panel already hide's with small screens, on medium sized screens the graph sizes are reduced by the lefthand panel and even with much larger screens the graph size is restricted. 

![image](https://user-images.githubusercontent.com/5606042/43365825-9794a464-932a-11e8-9857-292a9f13a8df.png)

Can we please make the lefthand panel permanently user collapsible and let it default to closed on smaller screens?

And also lift the maximum graph width when ` $fullwidth = true;` is set in settings.php.

**Comment by TrystanLea** [comment]
good idea, it might be worth exploring the use of the standard dark sidebar styling as used by the app, sync and soon to be updated config module for this - it has the option to show/hide as standard.

**Comment by glynhudson** [comment]
implemented in https://github.com/emoncms/graph/pull/73
