### ISSUE TITLE
Collapsible stats table

### ISSUE THREAD

**Issue by pb66** [emoncms/graph#29]
When working with a large number of feeds the page becomes very long and awkward to use. for example the page below is one that I typically encounter and want to zoom in on a point and then download the csv, that's a lot of scrolling up and down due to the stats table.

It would be useful if the stats table was collapsible, (perhaps even collapsed by default so the graphing area could be bigger).

![image](https://user-images.githubusercontent.com/5606042/45584634-0a93ce80-b8cf-11e8-9ced-0570caec7b2e.png)

**Comment by TrystanLea** [comment]
good idea!

**Comment by emrysr** [comment]
issue fixed in pull request #54
