### ISSUE TITLE
Statistics missing

### ISSUE THREAD

**Issue by borpin** [emoncms/graph#35]
The statistics (mean etc) of the old visualisation are missing in graph Module.

**Comment by glynhudson** [comment]
The Graph view does show statistics, just click "Show Statistics" 

![emoncms - graph 1](https://user-images.githubusercontent.com/758844/48382171-b5f6af00-e6d7-11e8-8203-a98db53ae676.png)
![screenshot 2018-11-13 at 00 04 22](https://user-images.githubusercontent.com/758844/48382175-b8590900-e6d7-11e8-8cce-0c58dfc6d02b.png)

Do you think this needs to be made more obvious?

**Comment by borpin** [comment]
White text on Grey is really poor UI especially for those with impaired sight (which isn't me but we look at lot at this at work).

Yes, the text needs to have greater contrast.
