### ISSUE TITLE
position of tooltip and feeds panel

### ISSUE THREAD

**Issue by djh42** [emoncms/graph#38]
The tooltip showing an individual data value and time is very useful. When the browser window is narrow enough that the feeds panel hides and the graph fills the full width of the browser window, it also sensibly adjusts its position (moves right relatively) so it is not clipped by the left edge of the browser window when the data point is near the left side of the graph.

BUT ... when the feeds panel is displayed, either because the browser is wide or because the user has chosen to overlay it on the graph, the tooltip is displayed BEHIND the feeds panel where it cannot be read.

The tootltip should either be moved right so it is completely visible (best) or displayed in front of the feeds panel instead of behind it.

**Comment by TrystanLea** [comment]
Thanks @djh42 good point

**Comment by glynhudson** [comment]
Fixed by https://github.com/emoncms/graph/pull/42
