### ISSUE TITLE
Cannot read property 1 of undefined error

### ISSUE THREAD

**Issue by glynhudson** [emoncms/graph#46]
While zooming into power view graph using a MyElectric 2 dashboards:

![selection_071](https://user-images.githubusercontent.com/758844/51253604-b68d1980-1996-11e9-979f-f8d1eabd6f4a.jpg)
![selection_070](https://user-images.githubusercontent.com/758844/51253605-b68d1980-1996-11e9-814a-e2b174208c35.jpg)

**Comment by pb66** [comment]
Line 492 of which file?
The line contaning the path and file name isn't visible.
Should this issue not be raised in emoncms/app if it's from the my electric 2 app?

**Comment by glynhudson** [comment]
This issue has now been fixed
