### ISSUE TITLE
js error when user logged out

### ISSUE THREAD

**Issue by emrysr** [emoncms/graph#83]
![delwedd](https://user-images.githubusercontent.com/1466013/57524436-ade29980-731f-11e9-92ae-a6f35916333e.png)

this occurs when visiting `/emoncms/graph` if you're logged out

**Comment by emrysr** [comment]
also these two errors are shown when a logged out user tries to visit a specific feed's graph page
eg: `/emoncms/graph/125`

[first]
![delwedd](https://user-images.githubusercontent.com/1466013/57524655-5a248000-7320-11e9-9b82-6c5e7d697f3c.png)

[second]
![delwedd](https://user-images.githubusercontent.com/1466013/57524661-5ee93400-7320-11e9-8209-c28cdf67c507.png)

**Comment by chaveiro** [comment]
Thanks for the explanation. Understood
